
INSERT INTO webhook_variaveis_disponiveis (evento, chave, label, categoria) VALUES
('atividade_comentada', 'tipo', 'Tipo', 'geral'),
('atividade_comentada', 'atividade_id', 'ID da Atividade', 'identificação'),
('atividade_comentada', 'titulo', 'Título', 'geral'),
('atividade_comentada', 'comentario', 'Comentário', 'conteúdo'),
('atividade_comentada', 'autor_nome', 'Nome do Autor', 'autor'),
('atividade_comentada', 'autor_id', 'ID do Autor', 'autor'),
('atividade_criada_por_superadmin', 'acao', 'Ação', 'geral'),
('atividade_criada_por_superadmin', 'atividade_id', 'ID da Atividade', 'identificação'),
('atividade_criada_por_superadmin', 'titulo', 'Título', 'geral'),
('atividade_criada_por_superadmin', 'tipo', 'Tipo', 'geral'),
('atividade_criada_por_superadmin', 'categoria', 'Categoria', 'geral'),
('atividade_criada_por_superadmin', 'status', 'Status', 'geral'),
('atividade_criada_por_superadmin', 'criado_por_nome', 'Nome do Criador', 'autor'),
('atividade_criada_por_superadmin', 'criado_por_id', 'ID do Criador', 'autor'),
('corretor_aprovado', 'user_id', 'ID do Usuário', 'identificação'),
('corretor_aprovado', 'email', 'Email', 'contato'),
('corretor_aprovado', 'nome', 'Nome', 'geral'),
('corretor_aprovado', 'creci', 'CRECI', 'dados'),
('corretor_aprovado', 'imobiliaria', 'Imobiliária', 'dados'),
('corretor_aprovado', 'empreendimentos', 'Empreendimentos', 'dados'),
('imobiliaria_cadastrada', 'id', 'ID', 'identificação'),
('imobiliaria_cadastrada', 'nome', 'Nome', 'geral'),
('imobiliaria_cadastrada', 'cnpj', 'CNPJ', 'dados'),
('imobiliaria_cadastrada', 'email', 'Email', 'contato'),
('imobiliaria_cadastrada', 'telefone', 'Telefone', 'contato'),
('negociacao_movida', 'negociacao_id', 'ID da Negociação', 'identificação'),
('negociacao_movida', 'codigo', 'Código', 'identificação'),
('negociacao_movida', 'etapa_anterior', 'Etapa Anterior', 'movimentação'),
('negociacao_movida', 'etapa_nova', 'Etapa Nova', 'movimentação'),
('negociacao_movida', 'cliente', 'Cliente', 'geral'),
('negociacao_movida', 'empreendimento', 'Empreendimento', 'geral'),
('negociacao_movida', 'valor_total', 'Valor Total', 'financeiro'),
('negociacao_fechada', 'negociacao_id', 'ID da Negociação', 'identificação'),
('negociacao_fechada', 'negociacao_codigo', 'Código', 'identificação'),
('negociacao_fechada', 'cliente_nome', 'Nome do Cliente', 'geral'),
('negociacao_fechada', 'empreendimento_nome', 'Empreendimento', 'geral'),
('negociacao_fechada', 'valor_total', 'Valor Total', 'financeiro'),
('negociacao_perdida', 'negociacao_id', 'ID da Negociação', 'identificação'),
('negociacao_perdida', 'negociacao_codigo', 'Código', 'identificação'),
('negociacao_perdida', 'cliente_nome', 'Nome do Cliente', 'geral'),
('negociacao_perdida', 'empreendimento_nome', 'Empreendimento', 'geral'),
('negociacao_perdida', 'valor_total', 'Valor Total', 'financeiro'),
('comentario_proposta', 'negociacao_id', 'ID da Negociação', 'identificação'),
('comentario_proposta', 'negociacao_codigo', 'Código Negociação', 'identificação'),
('comentario_proposta', 'proposta_numero', 'Número Proposta', 'identificação'),
('comentario_proposta', 'autor', 'Autor', 'autor'),
('comentario_proposta', 'comentario', 'Comentário', 'conteúdo'),
('comentario_proposta', 'origem', 'Origem', 'geral'),
('comentario_proposta', 'link', 'Link', 'geral'),
('comentario_proposta', 'cliente_nome', 'Nome do Cliente', 'geral'),
('comentario_proposta', 'empreendimento_nome', 'Empreendimento', 'geral'),
('meta_comercial_criada', 'competencia', 'Competência', 'geral'),
('meta_comercial_criada', 'empreendimento_id', 'ID Empreendimento', 'identificação'),
('meta_comercial_criada', 'criado_por_nome', 'Criado Por', 'autor'),
('contrato_assinado', 'contrato_id', 'ID do Contrato', 'identificação'),
('contrato_assinado', 'numero', 'Número', 'identificação'),
('contrato_assinado', 'signatario_nome', 'Nome Signatário', 'geral'),
('contrato_assinado', 'signatario_email', 'Email Signatário', 'contato'),
('assinatura_enviada', 'contrato_id', 'ID do Contrato', 'identificação'),
('assinatura_enviada', 'signatario_nome', 'Nome Signatário', 'geral'),
('assinatura_enviada', 'signatario_email', 'Email Signatário', 'contato'),
('assinatura_enviada', 'link_assinatura', 'Link de Assinatura', 'geral'),
('proposta_em_analise', 'negociacao_id', 'ID da Negociação', 'identificação'),
('proposta_em_analise', 'codigo', 'Código', 'identificação'),
('proposta_em_analise', 'valor_total', 'Valor Total', 'financeiro'),
('proposta_aprovada_incorporador', 'negociacao_id', 'ID da Negociação', 'identificação'),
('proposta_aprovada_incorporador', 'codigo', 'Código', 'identificação'),
('proposta_aprovada_incorporador', 'valor_total', 'Valor Total', 'financeiro'),
('proposta_aprovada_incorporador', 'aprovador_nome', 'Aprovador', 'autor'),
('proposta_contra_proposta', 'negociacao_id', 'ID da Negociação', 'identificação'),
('proposta_contra_proposta', 'codigo', 'Código', 'identificação'),
('proposta_contra_proposta', 'valor_total', 'Valor Total', 'financeiro'),
('briefing_triado', 'briefing_id', 'ID do Briefing', 'identificação'),
('briefing_triado', 'codigo', 'Código', 'identificação'),
('briefing_triado', 'tema', 'Tema', 'geral'),
('briefing_triado', 'cliente', 'Cliente', 'geral'),
('reserva_criada', 'reserva_id', 'ID da Reserva', 'identificação'),
('reserva_criada', 'protocolo', 'Protocolo', 'identificação'),
('reserva_criada', 'cliente_nome', 'Nome do Cliente', 'geral'),
('reserva_criada', 'empreendimento', 'Empreendimento', 'geral'),
('lead_convertido', 'lead_id', 'ID do Lead', 'identificação'),
('lead_convertido', 'cliente_id', 'ID do Cliente', 'identificação'),
('lead_convertido', 'nome', 'Nome', 'geral'),
('lead_convertido', 'email', 'Email', 'contato'),
('lead_convertido', 'telefone', 'Telefone', 'contato'),
('negociacao_criada', 'negociacao_id', 'ID da Negociação', 'identificação'),
('negociacao_criada', 'codigo', 'Código', 'identificação'),
('negociacao_criada', 'cliente_nome', 'Nome do Cliente', 'geral'),
('negociacao_criada', 'empreendimento', 'Empreendimento', 'geral'),
('negociacao_criada', 'valor_total', 'Valor Total', 'financeiro'),
('contrato_gerado', 'contrato_id', 'ID do Contrato', 'identificação'),
('contrato_gerado', 'numero', 'Número', 'identificação'),
('contrato_gerado', 'cliente_nome', 'Nome do Cliente', 'geral'),
('contrato_gerado', 'empreendimento', 'Empreendimento', 'geral'),
('ticket_aguardando_analise', 'ticket_id', 'ID do Ticket', 'identificação'),
('ticket_aguardando_analise', 'titulo', 'Título', 'geral'),
('ticket_aguardando_analise', 'status', 'Status', 'geral'),
('ticket_em_producao', 'ticket_id', 'ID do Ticket', 'identificação'),
('ticket_em_producao', 'titulo', 'Título', 'geral'),
('ticket_em_producao', 'status', 'Status', 'geral'),
('ticket_revisao', 'ticket_id', 'ID do Ticket', 'identificação'),
('ticket_revisao', 'titulo', 'Título', 'geral'),
('ticket_revisao', 'status', 'Status', 'geral'),
('ticket_aprovacao_cliente', 'ticket_id', 'ID do Ticket', 'identificação'),
('ticket_aprovacao_cliente', 'titulo', 'Título', 'geral'),
('ticket_aprovacao_cliente', 'status', 'Status', 'geral'),
('ticket_ajuste', 'ticket_id', 'ID do Ticket', 'identificação'),
('ticket_ajuste', 'titulo', 'Título', 'geral'),
('ticket_ajuste', 'status', 'Status', 'geral'),
('ticket_concluido', 'ticket_id', 'ID do Ticket', 'identificação'),
('ticket_concluido', 'titulo', 'Título', 'geral'),
('ticket_concluido', 'status', 'Status', 'geral')
ON CONFLICT (evento, chave) DO NOTHING;
