-- Variáveis de contrato preenchidas pela integração de propostas (NEXA).
insert into nexa_contrato_variaveis (chave, label, tipo, is_sistema, is_active, fonte_sugerida) values
  ('profissao_cliente','Profissão do comprador','texto',true,true,'proposta.buyer.profession'),
  ('renda_cliente','Renda bruta do comprador','texto',true,true,'proposta.buyer.grossIncome'),
  ('nacionalidade_cliente','Nacionalidade do comprador','texto',true,true,'proposta.buyer.nationality'),
  ('estado_civil_cliente','Estado civil do comprador','texto',true,true,'proposta.buyer.maritalStatus'),
  ('regime_bens','Regime de bens','texto',true,true,'proposta.buyer.propertyRegime'),
  ('nascimento_cliente','Nascimento do comprador','texto',true,true,'proposta.buyer.birthDate'),
  ('conjuge_nome','Cônjuge — nome','texto',true,true,'proposta.spouse.name'),
  ('conjuge_cpf','Cônjuge — CPF','texto',true,true,'proposta.spouse.cpf'),
  ('conjuge_rg','Cônjuge — RG','texto',true,true,'proposta.spouse.rg'),
  ('conjuge_email','Cônjuge — e-mail','texto',true,true,'proposta.spouse.email'),
  ('conjuge_profissao','Cônjuge — profissão','texto',true,true,'proposta.spouse.profession'),
  ('conjuge_renda','Cônjuge — renda','texto',true,true,'proposta.spouse.grossIncome'),
  ('conjuge_nascimento','Cônjuge — nascimento','texto',true,true,'proposta.spouse.birthDate'),
  ('unidade_area','Unidade — área privativa','texto',true,true,'proposta.unit.privateArea'),
  ('unidade_fase','Unidade — fase/torre','texto',true,true,'proposta.unit.towerPhase'),
  ('unidade_vagas','Unidade — vagas de garagem','texto',true,true,'proposta.unit.parkingSpots'),
  ('valor_unidade','Valor da unidade','texto',true,true,'proposta.unit.totalUnitValue'),
  ('corretor_nome','Corretor','texto',true,true,'proposta.broker.brokerName'),
  ('corretor_creci','CRECI do corretor','texto',true,true,'proposta.broker.creci'),
  ('corretor_telefone','Telefone do corretor','texto',true,true,'proposta.broker.brokerPhone'),
  ('imobiliaria','Imobiliária','texto',true,true,'proposta.broker.realEstateTeam'),
  ('proposta_codigo','Código da proposta','texto',true,true,'proposta.proposalCode'),
  ('pagamento_ato','Pagamento — Ato/Recursos próprios','texto',true,true,'proposta.payment'),
  ('pagamento_mensais','Pagamento — Parcelas mensais','texto',true,true,'proposta.payment'),
  ('pagamento_baloes','Pagamento — Balões','texto',true,true,'proposta.payment'),
  ('pagamento_financiamento','Pagamento — Financiamento CEF','texto',true,true,'proposta.payment'),
  ('pagamento_subsidio','Pagamento — Subsídio','texto',true,true,'proposta.payment'),
  ('pagamento_subsidio_entrada','Pagamento — Subsídio porta de entrada','texto',true,true,'proposta.payment'),
  ('pagamento_fgts','Pagamento — FGTS','texto',true,true,'proposta.payment'),
  ('pagamento_sinal','Pagamento — Sinal de reserva','texto',true,true,'proposta.payment'),
  ('pagamento_dacao','Pagamento — Dação','texto',true,true,'proposta.payment'),
  ('pagamento_total','Pagamento — Total geral','texto',true,true,'proposta.payment')
on conflict (chave) do nothing;
